### only in case openshift-operators-redhat namespace does not have an OperatorGroup
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-operators-redhat-
  namespace: openshift-operators-redhat
spec:
  upgradeStrategy: Default

