---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: netobserv-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: netobserv-operator
  namespace: netobserv-operator
spec:
  upgradeStrategy: Default

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: netobserv-operator
  namespace: netobserv-operator
spec:
  channel: stable
  installPlanApproval: Automatic #you can set this to manual if you want to control versions upgrade manually
  name: netobserv-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  #startingCSV: network-observability-operator.v1.2.0
