apiVersion: flows.netobserv.io/v1beta1
kind: FlowCollector
metadata:
  name: cluster
spec:
  agent:
    ebpf:
      cacheActiveTimeout: 5s
      cacheMaxFlows: 100000
      debug: {}
      excludeInterfaces:
      - lo
      imagePullPolicy: IfNotPresent
      kafkaBatchSize: 10485760
      logLevel: info
      resources:
        limits:
          memory: 800Mi
        requests:
          cpu: 100m
          memory: 50Mi
      sampling: 50
    type: EBPF ## EBPF or ipfix
  consolePlugin:
    imagePullPolicy: IfNotPresent
    logLevel: info
    port: 9001
    portNaming:
      enable: true
      portNames:
        "3100": loki
    quickFilters:
    - default: true
      filter:
        dst_namespace!: openshift-,netobserv  ## netobserv: this is how you named the namespace when you installed loki
        src_namespace!: openshift-,netobserv  ## same
      name: Applications
    - filter:
        dst_namespace: openshift-,netobserv ## netobserv: this is how you named the namespace when you installed loki
        src_namespace: openshift-,netobserv ## same
      name: Infrastructure
    - default: true
      filter:
        dst_kind: Pod
        src_kind: Pod
      name: Pods network
    - filter:
        dst_kind: Service
      name: Services network
    register: true
    replicas: 1
    resources:
      limits:
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 50Mi
  deploymentModel: DIRECT
  exporters: []
  loki:
    authToken: FORWARD
    batchSize: 10485760
    batchWait: 1s
    maxBackoff: 5s
    maxRetries: 2
    minBackoff: 1s
    staticLabels:
      app: netobserv-flowcollector
    statusTls:
      caCert:
        certFile: service-ca.crt
        name: lokistack-netobserv-ca-bundle  ##  lokistack-netobserv (preceeding -ca-bundle) is the name of the lokiStack CRD.
        namespace: ""
        type: configmap
      enable: false
      insecureSkipVerify: false
      userCert:
        certFile: tls.crt
        certKey: tls.key
        name: lokistack-netobserv-query-frontend-http ##  lokistack-netobserv (preceeding -query ) is the name of the lokiStack CRD.
        namespace: ""
        type: secret
    statusUrl: https://lokistack-netobserv-query-frontend-http.netobserv.svc:3100/  ## in this url lokistack-netobserv (preceeding -query) is the name of the lokiStack CRD. netobserv (succeeding http. ) is the namespace of Loki installation
    tenantID: network
    timeout: 10s
    tls:
      caCert:
        certFile: service-ca.crt
        name: lokistack-netobserv-gateway-ca-bundle  ##  lokistack-netobserv (preceeding -gateway ) is the name of the lokiStack CRD.
        namespace: ""
        type: configmap
      enable: true
      insecureSkipVerify: false
      userCert:
        namespace: ""
    url: https://lokistack-netobserv-gateway-http.netobserv.svc:8080/api/logs/v1/network  ## in this url lokistack-netobserv (preceeding -gateway) is the name of the lokiStack CRD. netobserv (succeeding http. ) is the namespace of Loki installation
  namespace: netobserv
  processor:
    conversationEndTimeout: 1m0s
    conversationHeartbeatInterval: 3m0s
    conversationTerminatingTimeout: 5s
    debug: {}
    dropUnusedFields: true
    enableKubeProbes: true
    healthPort: 8080
    logLevel: info
    logTypes: FLOWS
    metrics:
      ignoreTags: #can remove all or some of these tags and you will see metrics on the dashboard related to Netobserv
      - flows
      - bytes
      - packets
      server:
        port: 9102
        tls:
          type: DISABLED
    port: 2055
    profilePort: 6060
    resources:
      limits:
        memory: 800Mi
      requests:
        cpu: 100m
        memory: 100Mi
